---
name: python skeleton tests
on: [push]
jobs:
  run-format-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/run-format-checker

  run-style-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/stylecheck

  run-type-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/typecheck


  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/unittests
