---
name: python skeleton tests
on: [push]
jobs:
  run-format-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/run-format-checker

  run-style-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/stylecheck

  run-type-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y python3-venv
          python -m venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          scripts/ci/typecheck
#
#  run-unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - run: sudo apt-get install -y python3-venv
#      - run: python -m venv ve
#      - run: echo "ve/bin" >> $GITHUB_PATH
#      - run: pip install -r requirements.txt
#      - run: pip install -r dev-requirements.txt
#      - run: ./unittests
#
#  run-unit-tests-under-coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - run: sudo apt-get install -y python3-venv
#      - run: python -m venv ve
#      - run: echo "ve/bin" >> $GITHUB_PATH
#      - run: pip install -r requirements.txt
#      - run: pip install -r dev-requirements.txt
#      - run: ./unittests_coverage
